package com.csm.straining.dataaccess.entity.contact;

import java.util.Date;

public class Follow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow.id
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow.userID
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Long userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow.followID
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Long followID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow.createAt
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow.status
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow.id
     *
     * @return the value of tb_follow.id
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow.id
     *
     * @param id the value for tb_follow.id
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow.userID
     *
     * @return the value of tb_follow.userID
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow.userID
     *
     * @param userID the value for tb_follow.userID
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow.followID
     *
     * @return the value of tb_follow.followID
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Long getFollowID() {
        return followID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow.followID
     *
     * @param followID the value for tb_follow.followID
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setFollowID(Long followID) {
        this.followID = followID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow.createAt
     *
     * @return the value of tb_follow.createAt
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow.createAt
     *
     * @param createAt the value for tb_follow.createAt
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow.status
     *
     * @return the value of tb_follow.status
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow.status
     *
     * @param status the value for tb_follow.status
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}