package com.csm.straining.dataaccess.entity.contact;

import java.util.Date;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.id
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.userID
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Long userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.groupName
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.memberCount
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Integer memberCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.createAt
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.status
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.id
     *
     * @return the value of tb_group.id
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.id
     *
     * @param id the value for tb_group.id
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.userID
     *
     * @return the value of tb_group.userID
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.userID
     *
     * @param userID the value for tb_group.userID
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.groupName
     *
     * @return the value of tb_group.groupName
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.groupName
     *
     * @param groupName the value for tb_group.groupName
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.memberCount
     *
     * @return the value of tb_group.memberCount
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Integer getMemberCount() {
        return memberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.memberCount
     *
     * @param memberCount the value for tb_group.memberCount
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setMemberCount(Integer memberCount) {
        this.memberCount = memberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.createAt
     *
     * @return the value of tb_group.createAt
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.createAt
     *
     * @param createAt the value for tb_group.createAt
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.status
     *
     * @return the value of tb_group.status
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.status
     *
     * @param status the value for tb_group.status
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}