package com.csm.straining.dataaccess.entity.article;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.id
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.userID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Long userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.title
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.content
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.createAt
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.status
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.readCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Integer readCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.likeCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.dislikeCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Integer dislikeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.commentCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Integer commentCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.id
     *
     * @return the value of tb_article.id
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.id
     *
     * @param id the value for tb_article.id
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.userID
     *
     * @return the value of tb_article.userID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.userID
     *
     * @param userID the value for tb_article.userID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.title
     *
     * @return the value of tb_article.title
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.title
     *
     * @param title the value for tb_article.title
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.content
     *
     * @return the value of tb_article.content
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.content
     *
     * @param content the value for tb_article.content
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.createAt
     *
     * @return the value of tb_article.createAt
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.createAt
     *
     * @param createAt the value for tb_article.createAt
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.status
     *
     * @return the value of tb_article.status
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.status
     *
     * @param status the value for tb_article.status
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.readCount
     *
     * @return the value of tb_article.readCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.readCount
     *
     * @param readCount the value for tb_article.readCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.likeCount
     *
     * @return the value of tb_article.likeCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.likeCount
     *
     * @param likeCount the value for tb_article.likeCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.dislikeCount
     *
     * @return the value of tb_article.dislikeCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Integer getDislikeCount() {
        return dislikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.dislikeCount
     *
     * @param dislikeCount the value for tb_article.dislikeCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setDislikeCount(Integer dislikeCount) {
        this.dislikeCount = dislikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.commentCount
     *
     * @return the value of tb_article.commentCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.commentCount
     *
     * @param commentCount the value for tb_article.commentCount
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }
}