package com.csm.straining.dataaccess.entity.article;

import java.util.Date;

public class ArticleComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_comment.id
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_comment.articleID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Long articleID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_comment.userID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Long userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_comment.replyID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Long replyID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_comment.content
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_comment.createAt
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_comment.status
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_comment.id
     *
     * @return the value of tb_article_comment.id
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_comment.id
     *
     * @param id the value for tb_article_comment.id
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_comment.articleID
     *
     * @return the value of tb_article_comment.articleID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Long getArticleID() {
        return articleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_comment.articleID
     *
     * @param articleID the value for tb_article_comment.articleID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setArticleID(Long articleID) {
        this.articleID = articleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_comment.userID
     *
     * @return the value of tb_article_comment.userID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_comment.userID
     *
     * @param userID the value for tb_article_comment.userID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_comment.replyID
     *
     * @return the value of tb_article_comment.replyID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Long getReplyID() {
        return replyID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_comment.replyID
     *
     * @param replyID the value for tb_article_comment.replyID
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setReplyID(Long replyID) {
        this.replyID = replyID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_comment.content
     *
     * @return the value of tb_article_comment.content
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_comment.content
     *
     * @param content the value for tb_article_comment.content
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_comment.createAt
     *
     * @return the value of tb_article_comment.createAt
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_comment.createAt
     *
     * @param createAt the value for tb_article_comment.createAt
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_comment.status
     *
     * @return the value of tb_article_comment.status
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_comment.status
     *
     * @param status the value for tb_article_comment.status
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}