package com.csm.straining.dataaccess.entity.training;

import java.util.Date;

public class TrainingItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training_item.id
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training_item.trainingID
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Long trainingID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training_item.count
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training_item.breakTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer breakTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training_item.createAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training_item.id
     *
     * @return the value of tb_training_item.id
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training_item.id
     *
     * @param id the value for tb_training_item.id
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training_item.trainingID
     *
     * @return the value of tb_training_item.trainingID
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Long getTrainingID() {
        return trainingID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training_item.trainingID
     *
     * @param trainingID the value for tb_training_item.trainingID
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setTrainingID(Long trainingID) {
        this.trainingID = trainingID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training_item.count
     *
     * @return the value of tb_training_item.count
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training_item.count
     *
     * @param count the value for tb_training_item.count
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training_item.breakTime
     *
     * @return the value of tb_training_item.breakTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getBreakTime() {
        return breakTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training_item.breakTime
     *
     * @param breakTime the value for tb_training_item.breakTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setBreakTime(Integer breakTime) {
        this.breakTime = breakTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training_item.createAt
     *
     * @return the value of tb_training_item.createAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training_item.createAt
     *
     * @param createAt the value for tb_training_item.createAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}