package com.csm.straining.dataaccess.entity.training;

import java.util.Date;

public class Training {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.id
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.userID
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Long userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.type
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.beginAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Date beginAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.finishAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Date finishAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.presetCount
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer presetCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.presetGroup
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer presetGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.perBreakTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer perBreakTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.location
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.drinking
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer drinking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.gear
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer gear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.actualCount
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer actualCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.actualGroup
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer actualGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.actualBreakTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer actualBreakTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.actualConsumTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Integer actualConsumTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.status
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_training.createAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.id
     *
     * @return the value of tb_training.id
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.id
     *
     * @param id the value for tb_training.id
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.userID
     *
     * @return the value of tb_training.userID
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.userID
     *
     * @param userID the value for tb_training.userID
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.type
     *
     * @return the value of tb_training.type
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.type
     *
     * @param type the value for tb_training.type
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.beginAt
     *
     * @return the value of tb_training.beginAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Date getBeginAt() {
        return beginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.beginAt
     *
     * @param beginAt the value for tb_training.beginAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setBeginAt(Date beginAt) {
        this.beginAt = beginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.finishAt
     *
     * @return the value of tb_training.finishAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Date getFinishAt() {
        return finishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.finishAt
     *
     * @param finishAt the value for tb_training.finishAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setFinishAt(Date finishAt) {
        this.finishAt = finishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.presetCount
     *
     * @return the value of tb_training.presetCount
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getPresetCount() {
        return presetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.presetCount
     *
     * @param presetCount the value for tb_training.presetCount
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setPresetCount(Integer presetCount) {
        this.presetCount = presetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.presetGroup
     *
     * @return the value of tb_training.presetGroup
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getPresetGroup() {
        return presetGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.presetGroup
     *
     * @param presetGroup the value for tb_training.presetGroup
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setPresetGroup(Integer presetGroup) {
        this.presetGroup = presetGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.perBreakTime
     *
     * @return the value of tb_training.perBreakTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getPerBreakTime() {
        return perBreakTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.perBreakTime
     *
     * @param perBreakTime the value for tb_training.perBreakTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setPerBreakTime(Integer perBreakTime) {
        this.perBreakTime = perBreakTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.location
     *
     * @return the value of tb_training.location
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.location
     *
     * @param location the value for tb_training.location
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setLocation(Integer location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.drinking
     *
     * @return the value of tb_training.drinking
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getDrinking() {
        return drinking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.drinking
     *
     * @param drinking the value for tb_training.drinking
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setDrinking(Integer drinking) {
        this.drinking = drinking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.gear
     *
     * @return the value of tb_training.gear
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getGear() {
        return gear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.gear
     *
     * @param gear the value for tb_training.gear
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setGear(Integer gear) {
        this.gear = gear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.actualCount
     *
     * @return the value of tb_training.actualCount
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getActualCount() {
        return actualCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.actualCount
     *
     * @param actualCount the value for tb_training.actualCount
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setActualCount(Integer actualCount) {
        this.actualCount = actualCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.actualGroup
     *
     * @return the value of tb_training.actualGroup
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getActualGroup() {
        return actualGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.actualGroup
     *
     * @param actualGroup the value for tb_training.actualGroup
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setActualGroup(Integer actualGroup) {
        this.actualGroup = actualGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.actualBreakTime
     *
     * @return the value of tb_training.actualBreakTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getActualBreakTime() {
        return actualBreakTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.actualBreakTime
     *
     * @param actualBreakTime the value for tb_training.actualBreakTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setActualBreakTime(Integer actualBreakTime) {
        this.actualBreakTime = actualBreakTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.actualConsumTime
     *
     * @return the value of tb_training.actualConsumTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Integer getActualConsumTime() {
        return actualConsumTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.actualConsumTime
     *
     * @param actualConsumTime the value for tb_training.actualConsumTime
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setActualConsumTime(Integer actualConsumTime) {
        this.actualConsumTime = actualConsumTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.status
     *
     * @return the value of tb_training.status
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.status
     *
     * @param status the value for tb_training.status
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_training.createAt
     *
     * @return the value of tb_training.createAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_training.createAt
     *
     * @param createAt the value for tb_training.createAt
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}