package com.csm.straining.dataaccess.entity.training;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TrainingItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public TrainingItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTrainingIDIsNull() {
            addCriterion("trainingID is null");
            return (Criteria) this;
        }

        public Criteria andTrainingIDIsNotNull() {
            addCriterion("trainingID is not null");
            return (Criteria) this;
        }

        public Criteria andTrainingIDEqualTo(Long value) {
            addCriterion("trainingID =", value, "trainingID");
            return (Criteria) this;
        }

        public Criteria andTrainingIDNotEqualTo(Long value) {
            addCriterion("trainingID <>", value, "trainingID");
            return (Criteria) this;
        }

        public Criteria andTrainingIDGreaterThan(Long value) {
            addCriterion("trainingID >", value, "trainingID");
            return (Criteria) this;
        }

        public Criteria andTrainingIDGreaterThanOrEqualTo(Long value) {
            addCriterion("trainingID >=", value, "trainingID");
            return (Criteria) this;
        }

        public Criteria andTrainingIDLessThan(Long value) {
            addCriterion("trainingID <", value, "trainingID");
            return (Criteria) this;
        }

        public Criteria andTrainingIDLessThanOrEqualTo(Long value) {
            addCriterion("trainingID <=", value, "trainingID");
            return (Criteria) this;
        }

        public Criteria andTrainingIDIn(List<Long> values) {
            addCriterion("trainingID in", values, "trainingID");
            return (Criteria) this;
        }

        public Criteria andTrainingIDNotIn(List<Long> values) {
            addCriterion("trainingID not in", values, "trainingID");
            return (Criteria) this;
        }

        public Criteria andTrainingIDBetween(Long value1, Long value2) {
            addCriterion("trainingID between", value1, value2, "trainingID");
            return (Criteria) this;
        }

        public Criteria andTrainingIDNotBetween(Long value1, Long value2) {
            addCriterion("trainingID not between", value1, value2, "trainingID");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andBreakTimeIsNull() {
            addCriterion("breakTime is null");
            return (Criteria) this;
        }

        public Criteria andBreakTimeIsNotNull() {
            addCriterion("breakTime is not null");
            return (Criteria) this;
        }

        public Criteria andBreakTimeEqualTo(Integer value) {
            addCriterion("breakTime =", value, "breakTime");
            return (Criteria) this;
        }

        public Criteria andBreakTimeNotEqualTo(Integer value) {
            addCriterion("breakTime <>", value, "breakTime");
            return (Criteria) this;
        }

        public Criteria andBreakTimeGreaterThan(Integer value) {
            addCriterion("breakTime >", value, "breakTime");
            return (Criteria) this;
        }

        public Criteria andBreakTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("breakTime >=", value, "breakTime");
            return (Criteria) this;
        }

        public Criteria andBreakTimeLessThan(Integer value) {
            addCriterion("breakTime <", value, "breakTime");
            return (Criteria) this;
        }

        public Criteria andBreakTimeLessThanOrEqualTo(Integer value) {
            addCriterion("breakTime <=", value, "breakTime");
            return (Criteria) this;
        }

        public Criteria andBreakTimeIn(List<Integer> values) {
            addCriterion("breakTime in", values, "breakTime");
            return (Criteria) this;
        }

        public Criteria andBreakTimeNotIn(List<Integer> values) {
            addCriterion("breakTime not in", values, "breakTime");
            return (Criteria) this;
        }

        public Criteria andBreakTimeBetween(Integer value1, Integer value2) {
            addCriterion("breakTime between", value1, value2, "breakTime");
            return (Criteria) this;
        }

        public Criteria andBreakTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("breakTime not between", value1, value2, "breakTime");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("createAt is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("createAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("createAt =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("createAt <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("createAt >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("createAt >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("createAt <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("createAt <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("createAt in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("createAt not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("createAt between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("createAt not between", value1, value2, "createAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_training_item
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 24 01:38:45 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_training_item
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}