package com.csm.straining.dataaccess.mapper.training;

import com.csm.straining.dataaccess.entity.training.Training;
import com.csm.straining.dataaccess.entity.training.TrainingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrainingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    int countByExample(TrainingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    int deleteByExample(TrainingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    int insert(Training record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    int insertSelective(Training record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    List<Training> selectByExample(TrainingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    Training selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") Training record, @Param("example") TrainingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    int updateByExample(@Param("record") Training record, @Param("example") TrainingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    int updateByPrimaryKeySelective(Training record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_training
     *
     * @mbggenerated Sun Apr 24 01:38:45 CST 2016
     */
    int updateByPrimaryKey(Training record);
}