package com.csm.straining.dataaccess.mapper.user;

import com.csm.straining.dataaccess.entity.user.UserRank;
import com.csm.straining.dataaccess.entity.user.UserRankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    int countByExample(UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    int deleteByExample(UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    int insert(UserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    int insertSelective(UserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    List<UserRank> selectByExample(UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    UserRank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserRank record, @Param("example") UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    int updateByExample(@Param("record") UserRank record, @Param("example") UserRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    int updateByPrimaryKeySelective(UserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_rank
     *
     * @mbggenerated Fri Apr 15 10:47:54 CST 2016
     */
    int updateByPrimaryKey(UserRank record);
}