package com.csm.straining.dataaccess.entity.user;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.phone
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.username
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.signNature
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private String signNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.tags
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.location
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private Byte location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.occupation
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private Byte occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.avatar
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.createAt
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.status
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.phone
     *
     * @return the value of tb_user.phone
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.phone
     *
     * @param phone the value for tb_user.phone
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.username
     *
     * @return the value of tb_user.username
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.username
     *
     * @param username the value for tb_user.username
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.signNature
     *
     * @return the value of tb_user.signNature
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public String getSignNature() {
        return signNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.signNature
     *
     * @param signNature the value for tb_user.signNature
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setSignNature(String signNature) {
        this.signNature = signNature == null ? null : signNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.tags
     *
     * @return the value of tb_user.tags
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.tags
     *
     * @param tags the value for tb_user.tags
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.location
     *
     * @return the value of tb_user.location
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public Byte getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.location
     *
     * @param location the value for tb_user.location
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setLocation(Byte location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.occupation
     *
     * @return the value of tb_user.occupation
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public Byte getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.occupation
     *
     * @param occupation the value for tb_user.occupation
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setOccupation(Byte occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.avatar
     *
     * @return the value of tb_user.avatar
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.avatar
     *
     * @param avatar the value for tb_user.avatar
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.createAt
     *
     * @return the value of tb_user.createAt
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.createAt
     *
     * @param createAt the value for tb_user.createAt
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.status
     *
     * @return the value of tb_user.status
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.status
     *
     * @param status the value for tb_user.status
     *
     * @mbggenerated Sat Apr 09 15:40:12 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}