package com.csm.straining.dataaccess.mapper.moment;

import com.csm.straining.dataaccess.entity.moment.Moment;
import com.csm.straining.dataaccess.entity.moment.MomentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MomentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int countByExample(MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int deleteByExample(MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int insert(Moment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int insertSelective(Moment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    List<Moment> selectByExample(MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    Moment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") Moment record, @Param("example") MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByExample(@Param("record") Moment record, @Param("example") MomentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByPrimaryKeySelective(Moment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByPrimaryKey(Moment record);
}