package com.csm.straining.dataaccess.mapper.moment;

import com.csm.straining.dataaccess.entity.moment.MomentReply;
import com.csm.straining.dataaccess.entity.moment.MomentReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MomentReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int countByExample(MomentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int deleteByExample(MomentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int insert(MomentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int insertSelective(MomentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    List<MomentReply> selectByExample(MomentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    MomentReply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") MomentReply record, @Param("example") MomentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByExample(@Param("record") MomentReply record, @Param("example") MomentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByPrimaryKeySelective(MomentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_reply
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByPrimaryKey(MomentReply record);
}