package com.csm.straining.dataaccess.mapper.moment;

import com.csm.straining.dataaccess.entity.moment.MomentLike;
import com.csm.straining.dataaccess.entity.moment.MomentLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MomentLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int countByExample(MomentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int deleteByExample(MomentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int insert(MomentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int insertSelective(MomentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    List<MomentLike> selectByExample(MomentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    MomentLike selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") MomentLike record, @Param("example") MomentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByExample(@Param("record") MomentLike record, @Param("example") MomentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByPrimaryKeySelective(MomentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moment_like
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    int updateByPrimaryKey(MomentLike record);
}