package com.csm.straining.dataaccess.mapper.contact;

import com.csm.straining.dataaccess.entity.contact.Follow;
import com.csm.straining.dataaccess.entity.contact.FollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int countByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int deleteByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int insert(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int insertSelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    List<Follow> selectByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    Follow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") Follow record, @Param("example") FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int updateByExample(@Param("record") Follow record, @Param("example") FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int updateByPrimaryKeySelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_follow
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int updateByPrimaryKey(Follow record);
}