package com.csm.straining.dataaccess.mapper.contact;

import com.csm.straining.dataaccess.entity.contact.GroupUser;
import com.csm.straining.dataaccess.entity.contact.GroupUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int countByExample(GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int deleteByExample(GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int insert(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int insertSelective(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    List<GroupUser> selectByExample(GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    GroupUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") GroupUser record, @Param("example") GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int updateByExample(@Param("record") GroupUser record, @Param("example") GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int updateByPrimaryKeySelective(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group_user
     *
     * @mbggenerated Wed Apr 20 02:20:26 CST 2016
     */
    int updateByPrimaryKey(GroupUser record);
}