package com.csm.straining.dataaccess.entity.moment;

import java.util.Date;

public class Moment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment.id
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment.userID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Long userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment.content
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment.tranferID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Long tranferID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment.createAt
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment.status
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment.likeCount
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment.replyCount
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Integer replyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment.tranferCount
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Integer tranferCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment.id
     *
     * @return the value of tb_moment.id
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment.id
     *
     * @param id the value for tb_moment.id
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment.userID
     *
     * @return the value of tb_moment.userID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment.userID
     *
     * @param userID the value for tb_moment.userID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment.content
     *
     * @return the value of tb_moment.content
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment.content
     *
     * @param content the value for tb_moment.content
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment.tranferID
     *
     * @return the value of tb_moment.tranferID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Long getTranferID() {
        return tranferID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment.tranferID
     *
     * @param tranferID the value for tb_moment.tranferID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setTranferID(Long tranferID) {
        this.tranferID = tranferID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment.createAt
     *
     * @return the value of tb_moment.createAt
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment.createAt
     *
     * @param createAt the value for tb_moment.createAt
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment.status
     *
     * @return the value of tb_moment.status
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment.status
     *
     * @param status the value for tb_moment.status
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment.likeCount
     *
     * @return the value of tb_moment.likeCount
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment.likeCount
     *
     * @param likeCount the value for tb_moment.likeCount
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment.replyCount
     *
     * @return the value of tb_moment.replyCount
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Integer getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment.replyCount
     *
     * @param replyCount the value for tb_moment.replyCount
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setReplyCount(Integer replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment.tranferCount
     *
     * @return the value of tb_moment.tranferCount
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Integer getTranferCount() {
        return tranferCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment.tranferCount
     *
     * @param tranferCount the value for tb_moment.tranferCount
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setTranferCount(Integer tranferCount) {
        this.tranferCount = tranferCount;
    }
}