package com.csm.straining.dataaccess.entity.moment;

import java.util.Date;

public class MomentLike {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment_like.id
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment_like.momentID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Long momentID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment_like.userID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Long userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment_like.status
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moment_like.createAt
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment_like.id
     *
     * @return the value of tb_moment_like.id
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment_like.id
     *
     * @param id the value for tb_moment_like.id
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment_like.momentID
     *
     * @return the value of tb_moment_like.momentID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Long getMomentID() {
        return momentID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment_like.momentID
     *
     * @param momentID the value for tb_moment_like.momentID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setMomentID(Long momentID) {
        this.momentID = momentID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment_like.userID
     *
     * @return the value of tb_moment_like.userID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment_like.userID
     *
     * @param userID the value for tb_moment_like.userID
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment_like.status
     *
     * @return the value of tb_moment_like.status
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment_like.status
     *
     * @param status the value for tb_moment_like.status
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moment_like.createAt
     *
     * @return the value of tb_moment_like.createAt
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moment_like.createAt
     *
     * @param createAt the value for tb_moment_like.createAt
     *
     * @mbggenerated Fri Apr 22 23:06:16 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}