package com.csm.straining.dataaccess.mapper.article;

import com.csm.straining.dataaccess.entity.article.ArticleComment;
import com.csm.straining.dataaccess.entity.article.ArticleCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    int countByExample(ArticleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    int deleteByExample(ArticleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    int insert(ArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    int insertSelective(ArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    List<ArticleComment> selectByExample(ArticleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    ArticleComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") ArticleComment record, @Param("example") ArticleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    int updateByExample(@Param("record") ArticleComment record, @Param("example") ArticleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    int updateByPrimaryKeySelective(ArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_comment
     *
     * @mbggenerated Mon Apr 18 11:46:58 CST 2016
     */
    int updateByPrimaryKey(ArticleComment record);
}