package com.csm.straining.dataaccess.mapper.article;

import com.csm.straining.dataaccess.entity.article.ArticleLike;
import com.csm.straining.dataaccess.entity.article.ArticleLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    int countByExample(ArticleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    int deleteByExample(ArticleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    int insert(ArticleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    int insertSelective(ArticleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    List<ArticleLike> selectByExample(ArticleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    ArticleLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") ArticleLike record, @Param("example") ArticleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    int updateByExample(@Param("record") ArticleLike record, @Param("example") ArticleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    int updateByPrimaryKeySelective(ArticleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_like
     *
     * @mbggenerated Mon Apr 18 00:41:41 CST 2016
     */
    int updateByPrimaryKey(ArticleLike record);
}